import type { Metadata } from "next";
import '../styles/globals.css';
import { ProductProvider, CategoryProvider, UIProvider, CartProvider} from '../context';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <CartProvider>
          <CategoryProvider>
            <ProductProvider>
              <UIProvider>
                {children}
              </UIProvider>
            </ProductProvider>
          </CategoryProvider>
        </CartProvider>

      </body>
    </html>
  );
}
