import type { Metadata } from "next";
import "./globals.css";
import { IProduct} from "@/types";
import { fetchProducts } from "@/services/productService";
import { ProductsProvider } from "@/context";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const products:IProduct[] = await fetchProducts();
  return (
    <html lang="en">
      <body>
          <header>
            <Header/>
          </header>
          <main>
            <ProductsProvider products={products}>
              {children}
            </ProductsProvider>
          </main>
      </body>
    </html>
  );
}
