import type { Metadata } from "next";
import "./globals.css";
import { IUser,ICart,IProduct} from "@/types";
import { fetchCart } from "@/services/cartService";
import { fetchProducts } from "@/services/productService";
import { CartProvider, UIProvider, ProductsProvider } from "@/context";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user:IUser = {username: "123"}; // mock user
  const cart:ICart = await fetchCart(user); // mock cart
  const products:IProduct[] = await fetchProducts();

  return (
    <html lang="en">
      <body>
        <UIProvider>
          <header>
            <Header/>
          </header>
          <main>
            <CartProvider initialCart={cart}>
            <ProductsProvider products={products}>
              {children}
            </ProductsProvider>
            </CartProvider>
          </main>
        </UIProvider>
      </body>
    </html>
  );
}
