import { Product } from "../../types/types";

const products: Product[] = [
  {
    id: 1,
    brand: "Mavi",
    name: "Su İtici Bej Parka",
    description: "Mavi nin dış giyim koleksiyonundan Su İtici Bej Parka. Su itici özellikli kumaş. Stoperli, ayarlanabilir sabit kapüşon. Cırt cırt ile ayarlanabilir manşet. İki adet fermuarlı yan cep, iki adet kapalı ön cep, bir adet fermuarlı ön cep ve bir adet iç cep detayı.",
    subCategory: "Kaban",
    gender: "Erkek",
    category: "Dış Giyim",
    price: 3599.99,
    discount: 20,
    discountedPrice: 2879.99,
    stock: 2,
    imageUrl: "https://sky-static.mavi.com/mnresize/820/1162/0110350-70144_image_1.jpg",
    rating: 3.4,
  },
  {
    id: 2,
    brand: "M&S",
    name: "Regular Fit Kaban",
    description: "Bu şık mont, ayarlanabilir hunili yakasıyla farklı tarzlar yaratmanıza olanak tanır. Rahat kalıbı, katmanlı giyinmeyi kolaylaştırırken, astarı ekstra konfor sağlar. Kapalı düğme kapanışı, soğuk ve nemden korur. Ellerinizi soğuktan korumak ve essentiels eşyalarınızı saklamak için cepler idealdir. Ön kısmındaki düğme ve fermuar detayları şıklığı arttırırken, rahatlık da sağlanır.",
    subCategory: "Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    price: 4999.99,
    discount: 20,
    discountedPrice: 3999.99,
    stock: 8,
    imageUrl: "https://a53e12.a-cdn.akinoncloud.com/products/2024/11/08/725583/19a8d5f9-2308-4227-9d86-43584455f8e2_size1100x1430_cropCenter.jpg",
    rating: 4.2,  
  },
  {
    id: 3,
    brand: "Zara",
    name: "Kemerli Kruvaze Kaban",
    description: "%19 yünlü kumaştan üretilmiş relaxed fit kaban. Kruvaze ilikli, uzun kollu ve sivri yakalı. Kalça hizasında biyeli cepli, iç cepli ve aynı kumaştan kemerli. Arkası ortadan yırtmaçlı.",
    subCategory: "Kaban",
    gender: "Erkek",
    category: "Dış Giyim",
    price: 5690.00,
    discount: 40,
    discountedPrice: 3414.00,
    stock: 5,
    imageUrl: "https://static.zara.net/assets/public/e2c1/2174/1cc848cbba13/75b38773182c/04115164800-p/04115164800-p.jpg?ts=1733312063463&w=750",
    rating: 4.7,
  },
  {
    id: 4,
    brand: "M&S",
    name: "Tailored Fit Kaban",
    description: "Bu Terzi Usulü Tek Düğmeli Palto, Soğuk Günlerde Şıklığınızı Korumanız İçin Mükemmel Bir Seçim. Kolayca Giyilebilen Regular Fit Tasarımı, Uzun Kesimiyle Ekstra Sıcaklık Sağlar. Ön Kısımda Yer Alan İki Şık Düğme İle Kapanan Palto, Zarif Bir Görünüm Sunar. İki Adet Yandan Açılan Cep, Günlük Eşyalarınızı Pratik Bir Şekilde Saklamanızı Sağlar. Modern Detayları Ve Kullanışlı Yapısıyla Bu Palto, Gardırobunuzun Vazgeçilmez Bir Parçası Olacak. Hem Stil Hem De İşlevsellik Arayanlar İçin İdeal Bir Tercihtir.",
    subCategory: "Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    price: 4999.99,
    discount: 20,
    discountedPrice: 3999.99,
    stock: 2,
    imageUrl: "https://a53e12.a-cdn.akinoncloud.com/products/2024/09/30/717365/695fcd5d-12d9-45eb-a9bc-45664a337525_size900x1170_cropCenter.jpg",
    rating: 3.7,
  },
  {
    id: 5,
    brand: "Zara",
    name: "Yünlü Bukle Kaban Zw Collection",
    description: "Yünlü iplikten üretilmiş kısa kaban. Kruvaze yaka, uzun kollu, düğmeli manşet, önü cepli ve kruvaze düğmeli.",
    subCategory: "Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    price: 5690.00,
    discount: 50,
    discountedPrice: 2845.00,
    stock: 11,
    imageUrl: "https://static.zara.net/assets/public/a073/0c1f/f7b845209e2f/d73d2a12a62b/09867765712-a1/09867765712-a1.jpg?ts=1732034971001&w=316",
    rating: 3.9,
  },
  {
    id: 6,
    brand: "Mavi",
    name: "Bordo Suni Kürk",
    description: "Mavi Nin Kadın Koleksiyonundan Bordo Suni Kürk",
    subCategory: "Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    price: 3499.99,
    discount: 40,
    discountedPrice: 2099.99,
    stock: 7,
    imageUrl: "https://sky-static.mavi.com/mnresize/820/1162/1110585-70422_image_3.jpg",
    rating: 4.1,
  },
  {
    id: 7,
    brand: "M&S",
    name: "Stormwear™ Kapüşonlu Parka",
    description: "Pamuk karışımlı kumaştan üretilmiştir. Normal kalıp, kapüşonlu ve uzun kollu olarak tasarlanmıştır. Ön kısmında bulunan fermuar detaylı tasarım sayesinde kullanımı oldukça rahattır. Dış kısmında dört adet, iç kısmında ise iki adet olmak üzere toplam altı adet cep detayı bulunmaktadır. Thermowarmth™ dolgu teknolojisi, ekstra sıcaklık sağlarken suya dayanıklı Stormwear™ kumaş teknojimiz, hava nasıl olursa olsun kuru kalmanızı sağlar. Geri dönüştürülmüş polyester ve geri dönüştürülmüş polyester dolgu ile üretilmiştir. Giysilerimiz için kullanılan pamuğun tamamı sürdürülebilir kaynaklardan elde edilmiştir.",
    subCategory: "Kaban",
    gender: "Erkek",
    category: "Dış Giyim",
    price: 6999.99,
    discount: 30,
    discountedPrice: 4899.99,
    stock: 3,
    imageUrl: "https://a53e12.a-cdn.akinoncloud.com/products/2024/08/06/614204/336693a9-f942-4c63-9512-e55cc4ce5824_size1100x1430_cropCenter.jpg",
    rating: 3.8,
  },
  {
    id: 8,
    brand: "Mavi",
    name: "Sherpa Detaylı Suni Deri Kaban",
    description: "Mavi Nin Kadın Koleksiyonundan Sherpa Detaylı Uzun Suni Deri Kaban. İki Adet Ön Cep, Yakası Çıt Çıtlı Kemer Detayı Kapanabilir, Kol Dahil İçi Sherpa.",
    subCategory: "Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    price: 3499.99,
    discount: 40,
    discountedPrice: 2099.99,
    stock: 3,
    imageUrl: "https://sky-static.mavi.com/mnresize/820/1162/1110572-900_image_3.jpg",
    rating: 4.8,
  },
  {
    id: 9,
    brand: "M&S",
    name: "Regular Fit Kürklü Ceket",
    description: "Sıcak, Konforlu Ve Şık Bir Görünüm Sunan Bu Suni Kürk Bomber Ceket, Soğuk Hava Gardırobunuz İçin Mükemmel Bir Parça. Regular Fit Kesimiyle Rahat Bir Oturuş Sunan Bu Ceket, Sıcak Tutan Astarı Ve Beyzbol Tarzı Ribana Yakasıyla Dikkat Çekiyor. Ribana Manşetler Ve Etek Kısmı, Isıyı Hapsederken, Metal Fermuar Kapama Ve Ön Cepler İse Hem Şıklık Hem De Pratiklik Katıyor. Hem Günlük Hem De Özel Anlar İçin İdeal Bir Seçim Olan Bu Bomber Ceket, Stilinize Zarif Bir Dokunuş Ekleyecek.",
    subCategory: "Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    price: 4699.99,
    discount: 30,
    discountedPrice: 3289.99,
    stock: 6,
    imageUrl: "https://a53e12.a-cdn.akinoncloud.com/products/2024/09/26/717076/71dde4bb-4988-4663-a858-7d38550fd18a_size500x650_cropCenter.jpg",
    rating: 4.3,
  },
  {
    id: 10,
    brand: "Zara",
    name: "Suni Kürk Kaban",
    description: "Suni kürk kumaştan üretilmiş relaxed fit kaban. Çentikli yaka, uzun kollu, biyeli cepli, iç cepli ve önü düğme iliklemeli.",
    subCategory: "Kaban",
    gender: "Erkek",
    category: "Dış Giyim",
    price: 5990.00,
    discount: 30,
    discountedPrice: 4193.00,
    stock: 4,
    imageUrl: "https://static.zara.net/assets/public/7fe0/5f2d/e4664bbc867d/f45491ffcd43/04235967800-000-a4/04235967800-000-a4.jpg?ts=1733935210421&w=750",
    rating: 3.9,
  },
  {
    id: 11,
    brand: "Mavi",
    name: "Kapüşonlu Siyah Parka",
    description: "Mavi Black koleksiyonundan Kapüşonlu Siyah Parka. İki adet yan cep, iki adet çıt çıtlı kapaklı ön cep, bir adet fermuarlı ön cep, stoperli iple ayarlanabilir kapüşon, bir adet iç cep. Mavi nin karakteristik serisi Black, farklı tekniklerle zenginleştirilen logo uygulamalarıyla premium bir görünüm sunuyor. Tencel karışımlı kumaşlar, oversize kesimler, şık ve zamansız parçalarda hayat bulan yeni Mavi Black koleksiyonu şehirli erkeğin stil kodlarını yeniden tanımlıyor.",
    subCategory: "Kaban",
    gender: "Erkek",
    category: "Dış Giyim",
    price: 2599.99,
    discount: 20,
    discountedPrice: 2079.99,
    stock: 2,
    imageUrl: "https://sky-static.mavi.com/mnresize/820/1162/0110442-71379_image_1.jpg",
    rating: 3.6,
  },
  {
    id: 12,
    brand: "Zara",
    name: "ÇİFT TARAFLI ZW KOLEKSİYON CEKET",
    description: "Yaka detaylı, uzun kollu ceket. Önde yama cepli. Aynı renkte suni yünlü iç astarlı. Önden düğmeli.",
    subCategory: "kaban",
    gender: "kadın",
    category: "dış giyim",
    price: 3890.00,
    discount: 25,
    discountedPrice: 2917.50,
    stock: 3,
    imageUrl: "https://static.zara.net/assets/public/fca6/9b58/d9a5499a8585/0bb044690103/03548246800-p/03548246800-p.jpg?ts=1732181071707&w=316",
    rating: 4.4,
  }
];




export default products;
